services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - shared
      - db
    external_links:
      - templatemanager:grpc_url
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: db_name
      GRPC_CONTAINER: grpc_url
      GRPC_PORT: 50051
      CLIENTAUTH_API: https://dev-api.thegamechangercompany.io/client-auth
      URL_MAILER: https://dev-api.thegamechangercompany.io/mailer
      URL_MONGODB: https://dev-api.thegamechangercompany.io/api
#     SEGMENT_MICRO:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db

volumes:
  db_data:

networks:
   shared:
     name: shared_api_network
     external: true
   db:
