# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_transfer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'file_transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_transfer.proto\x12\x0ftemplatemanager\"8\n\x11UploadFileRequest\x12\x11\n\tfile_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"G\n\x12UploadFileResponse\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2h\n\x0fTemplateService\x12U\n\nUploadFile\x12\".templatemanager.UploadFileRequest\x1a#.templatemanager.UploadFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADFILEREQUEST']._serialized_start=40
  _globals['_UPLOADFILEREQUEST']._serialized_end=96
  _globals['_UPLOADFILERESPONSE']._serialized_start=98
  _globals['_UPLOADFILERESPONSE']._serialized_end=169
  _globals['_TEMPLATESERVICE']._serialized_start=171
  _globals['_TEMPLATESERVICE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
