apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamicore
  labels:
    app: gamicore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamicore
  template:
    metadata:
      labels:
        app: gamicore
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: gamicore
        image: tg2cregistry.azurecr.io/$(imageName):$(imageTag)  # Update with your image repository
        imagePullPolicy: IfNotPresent
        env:
#          - name: DB_USER
#            value: user
#          - name: DB_PASSWORD
#            value: password
#          - name: DB_HOST
#            value: db
#          - name: DB_NAME
#            value: db_name
          - name: SEGMENT_MICRO
            value: /gamicore
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 50051
          name: grpc
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: gamicore-config
        - secretRef:
            name: gamicore-secrets
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: gamicore
  labels:
    app: gamicore
  annotations:
    grpc.kubernetes.io/timeout-seconds: "120"
    grpc.kubernetes.io/keepalive-time-seconds: "60"
    grpc.kubernetes.io/keepalive-timeout-seconds: "20"
    grpc.kubernetes.io/max-message-size: "104857600"  # 100MB in bytes
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 50051
    targetPort: grpc
    protocol: TCP
    name: grpc
    appProtocol: grpc
  selector:
    app: gamicore