"""empty message

Revision ID: 03a0810606b8
Revises: 8f803c629661
Create Date: 2024-11-12 19:46:46.048903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a0810606b8'
down_revision: Union[str, None] = '8f803c629661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('client_address', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_projects_client_address'), 'projects', ['client_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_client_address'), table_name='projects')
    op.drop_column('projects', 'client_address')
    # ### end Alembic commands ###
