"""empty message

Revision ID: 0bc475ff018a
Revises: 9591177aa6e9
Create Date: 2024-11-21 07:58:58.146766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc475ff018a'
down_revision: Union[str, None] = '9591177aa6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_session_players', sa.Column('user_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arena_session_players', 'user_name')
    # ### end Alembic commands ###
