"""empty message

Revision ID: 1525d8504b4d
Revises: fbf102cba70d
Create Date: 2024-12-03 15:22:27.975694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1525d8504b4d'
down_revision: Union[str, None] = 'fbf102cba70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_sessions', sa.Column('super_game_master_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arena_sessions', 'super_game_master_id')
    # ### end Alembic commands ###
