"""empty message

Revision ID: 177e0e9b04ef
Revises: 0bc475ff018a
Create Date: 2024-11-21 10:04:18.882343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177e0e9b04ef'
down_revision: Union[str, None] = '0bc475ff018a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_session_players', sa.Column('email_status', sa.Enum('PENDING', 'SENT', 'FAILED', 'DELIVERED', name='emailstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arena_session_players', 'email_status')
    # ### end Alembic commands ###
