"""empty message

Revision ID: 21f33a946cce
Revises: 823165c90f3e
Create Date: 2024-11-19 12:20:54.939624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21f33a946cce'
down_revision: Union[str, None] = '823165c90f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arena_session_team_game_masters',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('arena_session_teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('arena_session_players', sa.Column('team_id', sa.String(length=36), nullable=True))
    op.add_column('arena_sessions', sa.Column('super_game_master_id', sa.String(length=36), nullable=True))
    op.add_column('arena_sessions', sa.Column('player_module_id', sa.String(length=36), nullable=True))
    op.add_column('arena_sessions', sa.Column('gamemaster_module_id', sa.String(length=36), nullable=True))
    op.add_column('arena_sessions', sa.Column('super_game_master_module_id', sa.String(length=36), nullable=True))
    op.add_column('project_modules', sa.Column('description', sa.String(length=255), nullable=True))
    op.alter_column('project_modules', 'type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('GAME', 'EXTENSION', name='moduletype'),
               existing_nullable=True)
    op.create_index(op.f('ix_project_modules_description'), 'project_modules', ['description'], unique=False)
    op.add_column('projects', sa.Column('module_gamemaster_id', sa.String(length=36), nullable=True))
    op.add_column('projects', sa.Column('module_super_game_master_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'module_super_game_master_id')
    op.drop_column('projects', 'module_gamemaster_id')
    op.drop_index(op.f('ix_project_modules_description'), table_name='project_modules')
    op.alter_column('project_modules', 'type',
               existing_type=sa.Enum('GAME', 'EXTENSION', name='moduletype'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('project_modules', 'description')
    op.drop_column('arena_sessions', 'super_game_master_module_id')
    op.drop_column('arena_sessions', 'gamemaster_module_id')
    op.drop_column('arena_sessions', 'player_module_id')
    op.drop_column('arena_sessions', 'super_game_master_id')
    op.drop_column('arena_session_players', 'team_id')
    op.drop_table('arena_session_teams')
    op.drop_table('arena_session_team_game_masters')
    # ### end Alembic commands ###
