"""empty message

Revision ID: 3577ab66e16d
Revises: 43839d8bb9e1
Create Date: 2024-12-04 15:34:32.456602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3577ab66e16d'
down_revision: Union[str, None] = '43839d8bb9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_arena_session_players_session_id'), 'arena_session_players', ['session_id'], unique=False)
    op.create_index(op.f('ix_arena_session_players_team_id'), 'arena_session_players', ['team_id'], unique=False)
    op.create_index(op.f('ix_arena_session_players_user_id'), 'arena_session_players', ['user_id'], unique=False)
    op.create_index(op.f('ix_arena_session_teams_session_id'), 'arena_session_teams', ['session_id'], unique=False)
    op.create_index(op.f('ix_arena_sessions_arena_id'), 'arena_sessions', ['arena_id'], unique=False)
    op.create_index(op.f('ix_arena_sessions_project_id'), 'arena_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_arena_sessions_super_game_master_id'), 'arena_sessions', ['super_game_master_id'], unique=False)
    op.create_index(op.f('ix_comment_likes_comment_id'), 'comment_likes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_likes_user_id'), 'comment_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_group_arenas_arena_id'), 'group_arenas', ['arena_id'], unique=False)
    op.create_index(op.f('ix_group_arenas_group_id'), 'group_arenas', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_arenas_user_id'), 'group_arenas', ['user_id'], unique=False)
    op.create_index(op.f('ix_group_projects_group_id'), 'group_projects', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_projects_project_id'), 'group_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_group_users_group_id'), 'group_users', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_users_user_id'), 'group_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_comments_project_id'), 'project_comments', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_comments_user_id'), 'project_comments', ['user_id'], unique=False)
    op.add_column('project_modules', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'description')
    op.drop_column('project_modules', 'description')
    op.drop_index(op.f('ix_project_comments_user_id'), table_name='project_comments')
    op.drop_index(op.f('ix_project_comments_project_id'), table_name='project_comments')
    op.drop_index(op.f('ix_group_users_user_id'), table_name='group_users')
    op.drop_index(op.f('ix_group_users_group_id'), table_name='group_users')
    op.drop_index(op.f('ix_group_projects_project_id'), table_name='group_projects')
    op.drop_index(op.f('ix_group_projects_group_id'), table_name='group_projects')
    op.drop_index(op.f('ix_group_arenas_user_id'), table_name='group_arenas')
    op.drop_index(op.f('ix_group_arenas_group_id'), table_name='group_arenas')
    op.drop_index(op.f('ix_group_arenas_arena_id'), table_name='group_arenas')
    op.drop_index(op.f('ix_comment_likes_user_id'), table_name='comment_likes')
    op.drop_index(op.f('ix_comment_likes_comment_id'), table_name='comment_likes')
    op.drop_index(op.f('ix_arena_sessions_super_game_master_id'), table_name='arena_sessions')
    op.drop_index(op.f('ix_arena_sessions_project_id'), table_name='arena_sessions')
    op.drop_index(op.f('ix_arena_sessions_arena_id'), table_name='arena_sessions')
    op.drop_index(op.f('ix_arena_session_teams_session_id'), table_name='arena_session_teams')
    op.drop_index(op.f('ix_arena_session_players_user_id'), table_name='arena_session_players')
    op.drop_index(op.f('ix_arena_session_players_team_id'), table_name='arena_session_players')
    op.drop_index(op.f('ix_arena_session_players_session_id'), table_name='arena_session_players')
    # ### end Alembic commands ###
