"""empty message

Revision ID: 43839d8bb9e1
Revises: 1525d8504b4d
Create Date: 2024-12-04 15:28:38.869723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43839d8bb9e1'
down_revision: Union[str, None] = '1525d8504b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_modules_description', table_name='project_modules')
    op.drop_column('project_modules', 'description')
    op.drop_index('ix_projects_description', table_name='projects')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_projects_description', 'projects', ['description'], unique=False)
    op.add_column('project_modules', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_project_modules_description', 'project_modules', ['description'], unique=False)
    # ### end Alembic commands ###
