"""second migration

Revision ID: 55c564caf7d5
Revises: 801c32fd71fa
Create Date: 2024-11-04 15:36:19.172103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '55c564caf7d5'
down_revision: Union[str, None] = '801c32fd71fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_modules_ibfk_1', 'project_modules', type_='foreignkey')
    op.drop_column('project_modules', 'accessType')
    op.drop_column('projects', 'periodType')
    op.drop_column('projects', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', mysql.ENUM('PENDING', 'PLAYING', 'ENDED'), nullable=True))
    op.add_column('projects', sa.Column('periodType', mysql.ENUM('FREE', 'RANGE'), nullable=True))
    op.add_column('project_modules', sa.Column('accessType', mysql.ENUM('AUTH', 'PUBLIC'), nullable=True))
    op.create_foreign_key('project_modules_ibfk_1', 'project_modules', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
