"""empty message

Revision ID: 60de946d2e25
Revises: c9d15a6e1c7e
Create Date: 2024-11-18 21:30:18.457365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60de946d2e25'
down_revision: Union[str, None] = 'c9d15a6e1c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_session_players', sa.Column('organisation_code', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_arena_session_players_organisation_code'), 'arena_session_players', ['organisation_code'], unique=False)
    op.add_column('arena_sessions', sa.Column('organisation_code', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_arena_sessions_organisation_code'), 'arena_sessions', ['organisation_code'], unique=False)
    op.add_column('arenas', sa.Column('organisation_code', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_arenas_organisation_code'), 'arenas', ['organisation_code'], unique=False)
    op.add_column('groups', sa.Column('organisation_code', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_groups_organisation_code'), 'groups', ['organisation_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_organisation_code'), table_name='groups')
    op.drop_column('groups', 'organisation_code')
    op.drop_index(op.f('ix_arenas_organisation_code'), table_name='arenas')
    op.drop_column('arenas', 'organisation_code')
    op.drop_index(op.f('ix_arena_sessions_organisation_code'), table_name='arena_sessions')
    op.drop_column('arena_sessions', 'organisation_code')
    op.drop_index(op.f('ix_arena_session_players_organisation_code'), table_name='arena_session_players')
    op.drop_column('arena_session_players', 'organisation_code')
    # ### end Alembic commands ###
