"""empty message

Revision ID: 755954124a65
Revises: 8f1b52798280
Create Date: 2024-11-19 02:02:44.457582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755954124a65'
down_revision: Union[str, None] = '8f1b52798280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_users', sa.Column('user_email', sa.String(length=255), nullable=True))
    op.add_column('group_users', sa.Column('first_name', sa.String(length=150), nullable=True))
    op.add_column('group_users', sa.Column('last_name', sa.String(length=150), nullable=True))
    op.add_column('group_users', sa.Column('picture', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('tags', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_projects_tags'), 'projects', ['tags'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_tags'), table_name='projects')
    op.drop_column('projects', 'created_at')
    op.drop_column('projects', 'tags')
    op.drop_column('group_users', 'picture')
    op.drop_column('group_users', 'last_name')
    op.drop_column('group_users', 'first_name')
    op.drop_column('group_users', 'user_email')
    # ### end Alembic commands ###
