"""empty message

Revision ID: 75b3a1cfd8ef
Revises: 03a0810606b8
Create Date: 2024-11-12 19:48:50.093845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '75b3a1cfd8ef'
down_revision: Union[str, None] = '03a0810606b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_client_address', table_name='projects')
    op.drop_column('projects', 'client_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('client_address', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_projects_client_address', 'projects', ['client_address'], unique=False)
    # ### end Alembic commands ###
