"""initial migration

Revision ID: 801c32fd71fa
Revises: 
Create Date: 2024-11-04 14:24:32.521992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801c32fd71fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('db_index', sa.String(length=36), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PLAYING', 'ENDED', name='projectstatus'), nullable=True),
    sa.Column('activation_status', sa.Enum('ACTIVE', 'DESACTIVE', name='projectactivationstatus'), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('periodType', sa.Enum('FREE', 'RANGE', name='periodtype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_client_name'), 'projects', ['client_name'], unique=False)
    op.create_index(op.f('ix_projects_db_index'), 'projects', ['db_index'], unique=False)
    op.create_index(op.f('ix_projects_description'), 'projects', ['description'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('project_modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('accessType', sa.Enum('AUTH', 'PUBLIC', name='accesstype'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_modules_name'), 'project_modules', ['name'], unique=False)
    op.create_index(op.f('ix_project_modules_project_id'), 'project_modules', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_modules_project_id'), table_name='project_modules')
    op.drop_index(op.f('ix_project_modules_name'), table_name='project_modules')
    op.drop_table('project_modules')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_description'), table_name='projects')
    op.drop_index(op.f('ix_projects_db_index'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
