"""empty message

Revision ID: 823165c90f3e
Revises: 755954124a65
Create Date: 2024-11-19 02:45:19.190272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '823165c90f3e'
down_revision: Union[str, None] = '755954124a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'activation_status',
               existing_type=mysql.ENUM('ACTIVE', 'DESACTIVE'),
               type_=sa.Enum('ACTIVE', 'INACTIVE', name='activationstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'activation_status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', name='activationstatus'),
               type_=mysql.ENUM('ACTIVE', 'DESACTIVE'),
               existing_nullable=True)
    # ### end Alembic commands ###
