"""empty message

Revision ID: 89284a87a9d7
Revises: cb0b5a4359c5
Create Date: 2024-11-29 17:11:56.247784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89284a87a9d7'
down_revision: Union[str, None] = 'cb0b5a4359c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_sessions', sa.Column('super_game_master_mail', sa.String(length=36), nullable=True))
    op.add_column('arena_sessions', sa.Column('email_status', sa.Enum('PENDING', 'SENT', 'FAILED', 'DELIVERED', name='emailstatus'), nullable=True))
    op.drop_column('arena_sessions', 'super_game_master_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_sessions', sa.Column('super_game_master_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_column('arena_sessions', 'email_status')
    op.drop_column('arena_sessions', 'super_game_master_mail')
    # ### end Alembic commands ###
