"""empty message

Revision ID: 8f803c629661
Revises: 8400f45fe46a
Create Date: 2024-11-11 23:02:20.485318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f803c629661'
down_revision: Union[str, None] = '8400f45fe46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_arenas', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.alter_column('project_modules', 'template_code',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.create_index(op.f('ix_project_modules_template_code'), 'project_modules', ['template_code'], unique=False)
    op.add_column('projects', sa.Column('organisation_code', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_projects_organisation_code'), 'projects', ['organisation_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_organisation_code'), table_name='projects')
    op.drop_column('projects', 'organisation_code')
    op.drop_index(op.f('ix_project_modules_template_code'), table_name='project_modules')
    op.alter_column('project_modules', 'template_code',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('group_arenas', 'user_id')
    # ### end Alembic commands ###
