"""empty message

Revision ID: 9591177aa6e9
Revises: 21f33a946cce
Create Date: 2024-11-20 15:24:19.704381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9591177aa6e9'
down_revision: Union[str, None] = '21f33a946cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('arena_sessions', sa.Column('activation_status', sa.Enum('ACTIVE', 'INACTIVE', name='activationstatus'), nullable=True))
    op.add_column('groups', sa.Column('activation_status', sa.Enum('ACTIVE', 'INACTIVE', name='activationstatus'), nullable=True))
    op.add_column('projects', sa.Column('game_trailer_url', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('allow_comments', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('replayable', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('public_leaderboard', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('restrict_playing_hours', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('playing_start_time', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('playing_end_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_projects_game_trailer_url'), 'projects', ['game_trailer_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_game_trailer_url'), table_name='projects')
    op.drop_column('projects', 'playing_end_time')
    op.drop_column('projects', 'playing_start_time')
    op.drop_column('projects', 'restrict_playing_hours')
    op.drop_column('projects', 'timezone')
    op.drop_column('projects', 'public_leaderboard')
    op.drop_column('projects', 'replayable')
    op.drop_column('projects', 'allow_comments')
    op.drop_column('projects', 'game_trailer_url')
    op.drop_column('groups', 'activation_status')
    op.drop_column('arena_sessions', 'activation_status')
    op.drop_table('project_comments')
    # ### end Alembic commands ###
