"""third migration

Revision ID: 98f3b3a9ec51
Revises: 55c564caf7d5
Create Date: 2024-11-04 16:05:43.854777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f3b3a9ec51'
down_revision: Union[str, None] = '55c564caf7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arena_session_players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arena_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('arena_id', sa.String(length=36), nullable=True),
    sa.Column('period_type', sa.Enum('FREE', 'RANGE', name='periodtype'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('access_status', sa.Enum('AUTH', 'GUEST', name='accessstatus'), nullable=False),
    sa.Column('session_status', sa.Enum('PENDING', 'PLAYING', 'ENDED', name='sessionstatus'), nullable=False),
    sa.Column('view_access', sa.Enum('ALL', 'GAME', 'SESSION', 'NONE', name='viewaccess'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arenas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_arenas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('arena_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    op.drop_table('group_users')
    op.drop_table('group_projects')
    op.drop_table('group_arenas')
    op.drop_table('arenas')
    op.drop_table('arena_sessions')
    op.drop_table('arena_session_players')
    # ### end Alembic commands ###
