"""empty message

Revision ID: c9d15a6e1c7e
Revises: e310be6ef7f4
Create Date: 2024-11-15 16:19:40.096316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d15a6e1c7e'
down_revision: Union[str, None] = 'e310be6ef7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_session_players', sa.Column('user_email', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('module_game_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_projects_module_game_id'), 'projects', ['module_game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_module_game_id'), table_name='projects')
    op.drop_column('projects', 'module_game_id')
    op.drop_column('arena_session_players', 'user_email')
    # ### end Alembic commands ###
