"""empty message

Revision ID: e310be6ef7f4
Revises: 70e6527bf8ac
Create Date: 2024-11-15 14:33:02.968505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e310be6ef7f4'
down_revision: Union[str, None] = '70e6527bf8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_session_players', sa.Column('module_id', sa.String(length=36), nullable=True))
    op.drop_column('arena_sessions', 'module_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_sessions', sa.Column('module_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_column('arena_session_players', 'module_id')
    # ### end Alembic commands ###
