"""empty message

Revision ID: e6625614f1a6
Revises: 81705bad515a
Create Date: 2024-11-21 14:15:48.954347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e6625614f1a6'
down_revision: Union[str, None] = '81705bad515a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arena_session_team_game_masters')
    op.add_column('arena_session_players', sa.Column('is_game_master', sa.Boolean(), nullable=True))
    op.drop_column('arena_session_players', 'module_id')
    op.add_column('arena_sessions', sa.Column('db_index', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_arena_sessions_db_index'), 'arena_sessions', ['db_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arena_sessions_db_index'), table_name='arena_sessions')
    op.drop_column('arena_sessions', 'db_index')
    op.add_column('arena_session_players', sa.Column('module_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_column('arena_session_players', 'is_game_master')
    op.create_table('arena_session_team_game_masters',
    sa.Column('team_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('team_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
