"""empty message

Revision ID: f150a62aa3a2
Revises: e6625614f1a6
Create Date: 2024-11-22 10:00:49.855177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f150a62aa3a2'
down_revision: Union[str, None] = 'e6625614f1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('email_status', sa.Enum('PENDING', 'SENT', 'FAILED', 'DELIVERED', name='emailstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'email_status')
    # ### end Alembic commands ###
