"""empty message

Revision ID: fbf102cba70d
Revises: 89284a87a9d7
Create Date: 2024-12-02 13:19:58.473243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf102cba70d'
down_revision: Union[str, None] = '89284a87a9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_modules', sa.Column('module_for', sa.Enum('ALL', 'PLAYER', 'GAMEMASTER', 'MODERATOR', 'MANAGER', 'OWNER', name='modulefortype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_modules', 'module_for')
    # ### end Alembic commands ###
