name: Push to Azure DevOps Repo

on:
  push:
    branches:
      - master  # The branch that triggers the action

jobs:
  push-to-azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure Git for Azure DevOps
      env:
        AZURE_DEVOPS_USERNAME: h.moukhlis
        AZURE_DEVOPS_PASSWORD: ${{ secrets.AZURE_DEVOPS_PASSWORD }}
      run: |
        git config --global user.name "Hamza Moukhlis"
        git config --global user.email "hamz.moukhlis@gmail.com"
        git remote add azure "https://$AZURE_DEVOPS_USERNAME:$AZURE_DEVOPS_PASSWORD@dev.azure.com/TG2C/core-micro/_git/core-micro"
    
    - name: Push changes to Azure DevOps
      env:
        AZURE_DEVOPS_USERNAME: h.moukhlis
        AZURE_DEVOPS_PASSWORD: ${{ secrets.AZURE_DEVOPS_PASSWORD }}
      run: |
        # Make sure you're pushing from the correct branch
        git push --force --progress azure master:feature-xyz  # Push master to 'dev' branch on Azure
