name: Push to Azure DevOps Repo

on:
  push:
    branches:
      - master  # Replace 'main' with the branch you want to trigger the action on

jobs:
  push-to-azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git for Azure DevOps
      env:
        AZURE_DEVOPS_USERNAME: h.moukhlis
        AZURE_DEVOPS_PASSWORD: 4Iq0Yd9mkpndLzPj3Jpa8H3VeVXszdGtA6gkGguyxXRgyujFxXYiJQQJ99AKACAAAAAZWs9bAAASAZDOXAk7
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git remote add azure "https://$AZURE_DEVOPS_USERNAME:$AZURE_DEVOPS_PASSWORD@dev.azure.com/TG2C/core-micro/_git/core-micro"

    - name: Push changes to Azure DevOps
      env:
        AZURE_DEVOPS_USERNAME: h.moukhlis
        AZURE_DEVOPS_PASSWORD: 4Iq0Yd9mkpndLzPj3Jpa8H3VeVXszdGtA6gkGguyxXRgyujFxXYiJQQJ99AKACAAAAAZWs9bAAASAZDOXAk7
      run: |
        git push azure dev  # Replace 'main' with the branch you want to push to
