name: Push to Azure DevOps Repo

on:
  push:
    branches:
      - master  # Replace 'main' with the branch you want to trigger the action on

jobs:
  push-to-azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch latest commit message from origin
      run: |
        # Fetch the latest commit from origin
        git fetch origin
        # Capture the latest commit message from origin/master
        echo "COMMIT_MSG=$(git log origin/master -1 --pretty=%B)" >> $GITHUB_ENV

    - name: Configure Git for Azure DevOps
      env:
        AZURE_DEVOPS_USERNAME: h.moukhlis
        AZURE_DEVOPS_PASSWORD: 4Iq0Yd9mkpndLzPj3Jpa8H3VeVXszdGtA6gkGguyxXRgyujFxXYiJQQJ99AKACAAAAAZWs9bAAASAZDOXAk7
      run: |
        git config --global user.name "Hamza moukhlis"
        git config --global user.email "hamz.moukhlis@gmail.com"
        echo $AZURE_DEVOPS_USERNAME
        git remote add azure "https://$AZURE_DEVOPS_USERNAME:$AZURE_DEVOPS_PASSWORD@dev.azure.com/TG2C/core-micro/_git/core-micro"
        git fetch azure

    - name: Push changes to Azure DevOps
      env:
        AZURE_DEVOPS_USERNAME: h.moukhlis
        AZURE_DEVOPS_PASSWORD: 4Iq0Yd9mkpndLzPj3Jpa8H3VeVXszdGtA6gkGguyxXRgyujFxXYiJQQJ99AKACAAAAAZWs9bAAASAZDOXAk7
      run: |
        git branch -r
        git add .
        git commit -m "$COMMIT_MSG" || echo "No changes to commit"
        git push azure dev  # Replace 'main' with the branch you want to push to
